language: scala

scala:
  - 2.12.8

jdk: oraclejdk8

sbt_args: "-J-Xmx2G"

script:
  - sbt clean +test:compile
  - sbt +test

sudo: required

services: docker

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.coursier
