language: scala

scala:
  - 2.12.6
  - 2.11.12

jdk: oraclejdk8

sbt_args: "-J-Xmx2G"

script:
  - sbt clean +test:compile
  - sbt +test
  - sbt makeSite

sudo: required

services: docker

after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && sbt docker:publishLocal && docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWD} && docker push flowtick/sysiphos:latest

deploy:
  provider: pages
  skip-cleanup: true
  github-token: ${GITHUB_TOKEN}  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: target/site
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = "false"

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.coursier
