language: scala

scala:
  - 2.12.6
  - 2.11.12

jdk: oraclejdk8

sbt_args: "-J-Xmx2G"

script:
  - sbt clean +test:compile
  - sbt +test

sudo: required

services: docker

after_success:
  - sbt docker:publishLocal
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWD}
  - docker push flowtick/sysiphos:latest

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.coursier
