version: '3.1'

services:

  db:
    image: mysql:5.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: sysiphos
    networks:
      main:
        aliases:
          - db
  # to have a look at the tables etc.
  adminer:
    image: adminer
    restart: always
    ports:
    - 9091:8080

  sysiphos-master:
    image: flowtick/sysiphos:latest
    depends_on:
      - db
    ports:
      - 1040:8080
      - 1050:8558
      - 1060:9095
    networks:
      main:
        aliases:
          - sysiphos-master
    environment:
      CLUSTER_ENABLED: "true"
      CLUSTER_IP: "sysiphos-master"
      ALLOW_MASTER: "on"
      ENDPOINT1_IP: "sysiphos-master"
      ENDPOINT2_IP: "sysiphos-worker"
      DATABASE_PROFILE: mysql
      DATABASE_URL: jdbc:mysql://db:3306/sysiphos
      DATABASE_USER: root
      DATABASE_PASSWORD: example
      STATS_ENABLED: "true"
      STATS_HOST: grafana

  sysiphos-worker:
    image: flowtick/sysiphos:latest
    depends_on:
      - db
    ports:
      - 2040:8080
      - 2050:8558
      - 2060:9095
    networks:
      main:
        aliases:
          - sysiphos-worker
    environment:
      CLUSTER_ENABLED: "true"
      CLUSTER_IP: "sysiphos-worker"
      ALLOW_MASTER: "off"
      ENDPOINT1_IP: "sysiphos-master"
      ENDPOINT2_IP: "sysiphos-worker"
      DATABASE_PROFILE: mysql
      DATABASE_URL: jdbc:mysql://db:3306/sysiphos
      DATABASE_USER: root
      DATABASE_PASSWORD: example
      STATS_ENABLED: "true"
      STATS_HOST: grafana

  grafana:
    image: kamon/grafana_graphite
    ports:
      - 3000:80
      - 3001:81
      - 8125:8125/udp
      - 8126:8126
      - 2003:2003
    networks:
      main:
        aliases:
          - grafana
networks:
  main: